name: google_atlas
description: Google Map Provider for Atlas, an extensible map abstraction for Flutter with support for multiple map providers
version: 0.0.9
authors:
  - Jorge Coca <jcocaramos@gmail.com>
  - Felix Angelov <felangelov@gmail.com>
  - Noah Mateen <noahmateen@gmail.com>
  - Tim Chabot <tchabot22@gmail.com>
repository: https://github.com/bmw-tech/atlas
issue_tracker: https://github.com/bmw-tech/atlas/issues
homepage: https://bmw-tech.github.io/atlas

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  atlas: 
    path: /Users/q485702/Desktop/flutter_projects/atlas/packages/atlas
  google_maps_flutter: ^0.5.19+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
